### ISSUE TITLE
Exiftool not killed upon exiting osxphotos

### ISSUE THREAD

**Issue by finestream** [RhetTbull/osxphotos#449] opened 2021-05-17 20:40 UTC
Hi RhetTbull,

Thank you for developing an maintaining this cool tool :) 

It seems that after exiting exiftool ist not killed and the process stays lingering. 

How to reproduce: run ps after executing osxphotos, you will get something like this:

<PID> ttys001    0:05.47 /usr/bin/perl -w /usr/local/bin/exiftool -stay_open True -@ - -common_args -n -P -G

Not a big issue, probably also quite easy to fix.

**Comment by RhetTbull** [comment] 2021-05-17 20:58
Thanks!  I'll take a look -- this is not the intended behavior.  For efficiency, osxphotos keeps the exiftool process open while osxphotos is running to avoid having to constantly re-spawn exiftool but it should be cleaned up when osxphotos exits.

**Comment by RhetTbull** [comment] 2021-05-17 22:09
@finestream what version of macOS are you running?  I looked at the code and this situation *shouldn't* happen as there's code that should run at exit to terminate the process.  I'll dig into this some more and see if I can replicate.

**Comment by finestream** [comment] 2021-05-18 06:26
Versions:
macOS 11.3.1 (BigSur on Intel CPU)
osxphotos, version 0.42.20
exiftool 12.16

**Comment by RhetTbull** [comment] 2021-05-18 13:46
Thanks.  I've recreated this issue and confirmed it exists on other versions of MacOS.  Also, today I learned from python [documentation](https://docs.python.org/3/reference/datamodel.html#object.__del__):

> It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits.

I was expecting the ExifTool class `__del__` method to cleanup the process when exiting but this doesn't always happen.  I'll add explicit code to cleanup exiftool before exiting osxphotos.

**Comment by RhetTbull** [comment] 2021-05-19 13:18
Learned something new today! Used [atexit](https://docs.python.org/3/library/atexit.html) to ensure exiftool processes got cleaned up when python interpreter is exiting.

**Comment by RhetTbull** [comment] 2021-05-19 13:32
Fixed in [v0.42.22](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.22)

**Closed by RhetTbull** 2021-05-19 13:32 UTC
Labels: bug
