### ISSUE TITLE
Add --force-update to update when metadata changed but photo did not

### ISSUE THREAD

**Issue by spencerc99** [RhetTbull/osxphotos#621] opened 2022-02-02 17:00 UTC
**Describe the bug**
I have a use case of continual export using `--update`. I noticed recently that this behavior changed where it no longer re-exports photos that have their photo metadata updated. I tried adding the `--ignore-signature` flag to handle this, but it looks like that does not trigger as well. 

**To Reproduce**
1. What' the full command line you used with osxphotos?
`osxphotos export --download-missing --album fits\ 🧢 --use-photokit --skip-live --skip-original-if-edited --filename "{created.date}:{original_name}" --update --ignore-signature --convert-to-jpeg --post-function ./scripts/transform_exported_fits_into_db.py::post_function --preview ./fits-export`

**Expected behavior**
Not sure if this is a bug or if I need to do something else to get this working, but my essential flow that I would like is for the `post_function` to be run for any photo that has changed since my last run (if the photo itself hasn't changed it doesn't _need_ to re-export, but it's fine if it does).

**Desktop (please complete the following information):**
OS Big Sur
osxphotos, version 0.45.3

**Comment by RhetTbull** [comment] 2022-02-02 17:28
Version 0.45 was a major rewrite of the export code so it could be a bug. However, the photo should only be updated if the actual image changed *or* if the metadata changed and you're also using --exiftool or --sidecar.  Does your post processing function rely on the metadata? 

If osxphotos was previously exporting photos when only metadata was updated and you weren't using --exiftool or --sidecar then that was actually a bug (which it sounds like your workflow depended on)

I'll investigate--in the meantime you could roll back to 0.44.x 

If 0.45 is working "correctly" as designed then I could add a flag to force --update to export if metadata changed even if the image itself didn't

**Comment by spencerc99** [comment] 2022-02-02 22:31
ah yeah my post-processing does rely on the metadata (specifically I peek at description and whether it is favorited to save in a JSON). adding --update to export if metadata changed even if image didn't would be perfect!

**Comment by RhetTbull** [comment] 2022-02-09 14:14
A --force-update option would force a photo to be updated (re-exported) if any of the metadata changed.  This can be implemented be using the exifdata table already in the export database to compare metadata.  exifdata is currently not set if --exiftool wasn't used though so that will require a code change in `PhotoExporter()`

**Comment by oPromessa** [comment] 2022-02-09 20:33
Possibly related, but also I guess more trickier to address, I've noticed the following behaviour:
1. Run export with `update` and `exiftool` and `keyword_template = [ "{keyword}", ]`
2. Run export again with `update` and `exiftool` and `keyword_template = [ "{keyword}", "{label}", ]`
3. The pics are not exported with the new
4. As it is not an actual **change of the pic**, nor a **change of metadata** but a **change of config/data to export** is not detected and processed.
    * I have a workaround which is to __delete__ the exported files (in batches to run this over several cycles) and run __export/update__

BTW, I noticed that `keyword_template` defines the values to be set by `exiftool` on the **keywords** and **subject** fields. I imagine this to be intentional.

**Comment by RhetTbull** [comment] 2022-02-09 20:45
> Possibly related, but also I guess more trickier to address, I've noticed the following behavior:

This is a bug.  When --exiftool is used with --update, osxphotos should consult the export database which stores a copy of the last computed metadata (with all templates like "{label}") expanded and should re-export the photos.  I thought I had a test case for this but apparently I don't or it's not catching this.  I'll take a look.  

> BTW, I noticed that keyword_template defines the values to be set by exiftool on the keywords and subject fields

Yes, this was by design because different apps treat these differently. I believe I modeled this on what Photos did when exporting with "export keywords as IPTC" but would have to go back and check Photos behavior.  I've tried to hit every EXIF, XMP, ITPC field that could be related so that metadata would be preserved regardless of which app was reaading the data.  But of course, with no metadata standard that's widely agreed on, this is very much a guessing game.

**Comment by RhetTbull** [comment] 2022-02-13 01:54
@spencerc99 I've added a `--force-update` in [v0.45.9](https://github.com/RhetTbull/osxphotos/releases/tag/v0.45.9)  This will force a re-export if any of the photo metadata changes (e.g. title, keywords, albums, etc.)  I had to update the export database schema to make this work so the first time you run it, it may re-export everything but once the database is upgraded, it should work as described in this issue.

**Comment by RhetTbull** [comment] 2022-02-13 02:07
I spoke too soon...hold off on updating for now.  After pushing the update I noticed some edge cases where this doesn't behave as expected.

**Comment by RhetTbull** [comment] 2022-02-13 05:10
OK, I think this is fixed in [v0.45.10](https://github.com/RhetTbull/osxphotos/releases/tag/v0.45.10).  The way `--force-update` works means you should always use `--force-update` or `--update` but not switch between them. When run with `--force-update`, osxphotos saves a hash of the photo's metadata to compare to the next time it's run.  The first time you run `--force-update` on an existing export, it will need to re-export all the photos because the metadata hash won't be computed yet.

**Comment by RhetTbull** [comment] 2022-02-17 15:56
It wouldn't hurt to use a fresh export folder.  If you don't osxphotos should delete the files that need to be re-exported.  

If you can wait a few days I'd do so as I'm in the middle of a refactor of all the "should a photo be updated" code (see #630 ) because there are some combinations of options that aren't handled 100% correctly in the current code. I have a design for a much better implementation but won't get to it until the weekend.

**Comment by spencerc99** [comment] 2022-02-17 16:03
That sounds amazing. No rush from my end — will happily await the refactor + update :) appreciate your dilligence on this front

**Comment by RhetTbull** [comment] 2022-02-21 17:41
@spencerc99 I've updated osxphotos to [v0.46.0](https://github.com/RhetTbull/osxphotos/releases/tag/v0.46.0) which is a major rewrite of the export / update logic.  I think you'll find --update/--force-update are working much better in this version but let me know if you run into any issues!

**Comment by spencerc99** [comment] 2022-02-26 03:11
upgraded and did a quick test and it works like a charm :) thanks so much!

**Comment by spencerc99** [comment] 2022-03-01 07:10
sorry to keep banging this one but I'm noticing some behavior that makes sense given the functionality you added but not exactly ideal. 

Basically, it seems like apple's tagging system may not be stable (labels, peopleCount)? and so I'm observing all of my photos getting re-exported without any intentional action from me. Wondering if there's any way to have another property to narrow down the set of metadata (really I only care about the ones that I change (i.e. description, favorite status). Wondering if you've encountered this apple issue before

**Comment by spencerc99** [comment] 2022-03-01 07:11
> sorry to keep banging this one but I'm noticing some behavior that makes sense given the functionality you added but not exactly ideal.
> 
> Basically, it seems like apple's tagging system may not be stable (labels, peopleCount)? and so I'm observing all of my photos getting re-exported without any intentional action from me. Wondering if there's any way to have another property to narrow down the set of metadata (really I only care about the ones that I change (i.e. description, favorite status). Wondering if you've encountered this apple issue before

Actually this just happened and I wonder if it's because I uploaded to the new Mac OSx yesterday.. On a repeated run immediately after it does not seem to change. Will keep an eye out for the next week to see if I run into this issue again!

**Comment by RhetTbull** [comment] 2022-03-01 07:26
> Basically, it seems like apple's tagging system may not be stable (labels, peopleCount)? a

That's correct. In particular, labels can be recomputed when there are changes to the photo library.  It's a process that runs in the background and if you updated MacOS, added a bunch of photos to the library, etc. they may get recomputed.

**Comment by RhetTbull** [comment] 2022-03-01 07:44
> Wondering if there's any way to have another property to narrow down the set of metadata (really I only care about the ones that I change (i.e. description, favorite status). Wondering if you've encountered this apple issue before

**Comment by RhetTbull** [comment] 2022-05-07 04:39
@spencerc99 in [v0.48.4](https://github.com/RhetTbull/osxphotos/releases/tag/v0.48.4) I've added a new `ExportResults.metadata_changed` property to `ExportResults` which gets passed to your `--post-function`.  This should allow you to get notification of any metadata changes, even for files that are not exported, when using --update.  For example:

```python
""" Example function for use with osxphotos export --post-function option """

from typing import Callable

from osxphotos import ExportResults, PhotoInfo


def post_function(
    photo: PhotoInfo, results: ExportResults, verbose: Callable, **kwargs
):
    for filename in results.metadata_changed:
        verbose(f"post_function: {filename} metadata changed (uuid={photo.uuid})")
```

**Closed** 2022-05-21 18:18 UTC
Labels: feature request
