### ISSUE TITLE
Newlines are converted to spaces in the description of an exported photo, but retained in a finder comment.

### ISSUE THREAD

**Issue by dssinger** [RhetTbull/osxphotos#513] opened 2021-08-29 02:02 UTC
If I put an `{lf}` or `{newline}` into --description-template, it is removed before being written to the exported photo, but using the same template for `--xattr-template findercomment` leaves the newline in the resulting comment.

Here's a script to test it:  
[lftest.zip](https://github.com/RhetTbull/osxphotos/files/7071769/lftest.zip)

and a small library with a single photo with both a title and description:
[during.zip](https://github.com/RhetTbull/osxphotos/files/7071771/during.zip)

Thanks.

**Comment by RhetTbull** [comment] 2021-08-29 03:48
Thanks -- the test script & sample library really help with debugging.  As best as I can tell, exiftool is stripping out the newline (I confirmed osxphotos does not do so) but I'll keep digging to confirm and figure out if there's a way to make sure the linefeed is preserved.

**Comment by RhetTbull** [comment] 2021-08-29 14:07
@all-contributors please add @dssinger for bug

**Comment by RhetTbull** [comment] 2021-08-29 14:26
I was wrong...osxphotos is removing the new lines before passing to exiftool:

https://github.com/RhetTbull/osxphotos/blob/8e2b76823686374cb056691991167431f6878d47/osxphotos/photoinfo/_photoinfo_export.py#L1874-L1880

This is due to the fact that the exiftool command interface I'm using barfs on embedded newlines.  I think there's a workaround for this with exiftool -- will explore.

**Comment by RhetTbull** [comment] 2021-08-29 17:11
I think I have this fixed.  Need to do some additional testing then will push a fix later today.

```
exiftool -j -G -XMP:Description /Users/rhet/Desktop/Test/pizza.jpg
[{
  "SourceFile": "/Users/rhet/Desktop/Test/pizza.jpg",
  "XMP:Description": "Pizza\nFrom Otto Portland"
}]
```

**Comment by RhetTbull** [comment] 2021-08-29 19:21
I think this is fixed in [v0.42.78](https://github.com/RhetTbull/osxphotos/releases/tag/v0.42.78)

**Comment by dssinger** [comment] 2021-08-29 23:38
It's fixed - thanks!  And thanks for osxphotos - it's immensely useful!

**Comment by RhetTbull** [comment] 2021-08-30 03:28
Great! Thanks for the feedback & the excellent issue write-ups -- the sample libraries + test scripts are immensely useful for tracking down these issues.

**Closed by RhetTbull** 2021-08-30 03:28 UTC
Labels: bug
