### ISSUE TITLE
GPS location not exported with exiftool

### ISSUE THREAD

**Issue by mccarverone** [RhetTbull/osxphotos#237] opened 2020-10-21 21:09 UTC
Hello, in the package interface I am experimenting with the `exiftool` parameter in the `export` method.

I changed the default GPS location in a photo and after exporting it with this parameter, I find that the photo still carries the original GPS location. I was wondering what the actual use is of the aforementioned parameter. Thanks

**Comment by RhetTbull** [comment] 2020-10-21 21:12
Sounds like a bug.  I'd expect this to export the updated GPS location.  I'll take a look.

**Comment by RhetTbull** [comment] 2020-10-22 02:36
I've replicated this behavior -- GPS location is not correctly being exported when `exiftool` is used.

**Comment by RhetTbull** [comment] 2020-10-22 05:35
@mccarverone  I believe this issue is fixed in [v0.35.5](https://github.com/RhetTbull/osxphotos/releases/tag/v0.35.5).  Let me know if this latest release doesn't fix the problem for you.

**Comment by mccarverone** [comment] 2020-10-22 06:27
It's perfect now, thanks

**Comment by mccarverone** [comment] 2020-10-23 07:15
Hello Rhet there is another quirky behaviour of the `exiftool` parameter: it does tag faces as keywords during export even though the `export` function was not launched with `use_persons_as_keywords`, this is not the expected behaviour in my opinion.

**Comment by RhetTbull** [comment] 2020-10-23 14:21
Are you certain it's the actual `IPTC:Keywords` field that contains the faces/persons? Looking at the code I don't see how this could happen.  The code does set `XMP:PersonInImage` to the persons and it sets `XMP:Subject` to both keywords and persons.  The reason for the latter is that is what previous versions of Photos did.  Prior to Photos 5, Photos would set `XMP:Subject` to keywords and persons but did not set `XMP:PersonInImage`.  Photos 5 now sets `XMP:PersonInImage` to the person and `XMP:Subject` to the keywords so in this regard, `osxphotos` is different.  Given the current behavior of Photos regarding `XMP:Subject`, I could change `osxphotos` to match and only record the person in `XMP:PersonInImage`.  Of course, Photos only does this if the user checks the "Include Title, Keywords, and Description" checkbox...note it says nothing about persons even though it does export this information.

<img width="531" alt="Screen Shot 2020-10-23 at 7 02 58 AM" src="https://user-images.githubusercontent.com/41546558/97015195-23382f00-1500-11eb-917f-f8eb31b7a091.png">

Is your expected behavior that *no information on persons* be exported if `use_persons_as_keywords=False`? I may need to update the documentation as there's not currently a way to exclude all information about persons from being exported with `exiftool` as I was trying to 1) ensure no metadata was lost on export and 2) match where possible the behavior of Photos.

**Comment by mccarverone** [comment] 2020-10-23 16:32
Hello, thanks for the articulated answer. I confirm that I was in fact finding `XMP:Subject` and `XMP:PersonInImage` so this is not a bug. I have no preferences about this, and since this is the default Apple Photo behaviour it makes sense to mimic it.
Honestly I didn't expect pieces of information concerning people to pour in the final exported picture without explicit parameters. But it's good to know. Thanks again

**Closed** 2020-11-30 20:54 UTC
Labels: bug
