### ISSUE TITLE
--exiftool causes warning even though metadata is written to exported photos

### ISSUE THREAD

**Issue by zeroboioioy** [RhetTbull/osxphotos#1104] opened 2023-06-28 15:34 UTC
Hi,

I am using osxphotos 0.60.5 and exiftools 12.63
```
osxphotos -v 
osxphotos, version 0.60.5
Python 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
macOS 13.4.0, arm64


exiftool -ver          
12.63
```

I do a simple export with exiftools, but no metadata is in the exported pictures:
`osxphotos export "/Users/0/Pictures/xxx" --exiftool --album "xxx"`

Tried exiftools with option"-v" and it shows the error message with every picture:
`WARNING - exiftool.py - 415 - error loading json returned by exiftool: Expecting value: line 1 column 1 (char 0)`

Any idea how to fix this as i am unable to export pictures from Apple Photos with any Metadata?

**Comment by RhetTbull** [comment] 2023-06-28 22:23
This is working for me on 13.4 / M1 with exiftool 12.60 (the latest production release). Please try exiftool 12.60 or earlier and see if you still get the warning.

**Comment by RhetTbull** [comment] 2023-06-29 04:39
I have not been able to reproduce this on macOS 13.4 with exiftool 12.60 (latest production version). Is this happening for every photo you try to export or just ones in the specific album? What is the format of the photo or video being exported? This error is expected for certain files which are not compatible with exiftool such as AVI but all common file formats should work as expected.

**Comment by zeroboioioy** [comment] 2023-06-29 04:58
I had exiftool 12.60 before and had the same errors. I then updated to 12.63 from the website to make sure it’s not an issue with exiftool. 

The files are jpg and I see in verbose mode that the information is read, but it seems to be unable to write it?

**Comment by RhetTbull** [comment] 2023-06-29 06:34
OK, try this to get some additional debug data:

Select one of the photos in question.

At the command line, run:

`osxphotos repl --selected`

This opens an interactive command line session with osxphotos.

At the `>>>` prompt, type:

`photos[0].exiftool.asdict()` then copy the output and paste back here or send it to me (email address on my Github profile).

Then with the same photo selected, type the following at the command line:

`osxphotos debug-dump --dump photos --selected > debug.txt`

and send the `debug.txt` file or attach it here.

This will contain sensitive info such as location so if that matters to you, edit the output first or select a photo that isn't sensitive.

**Comment by zeroboioioy** [comment] 2023-06-29 07:02
well, while using your commands and checking the file in Finder, i found something:

When i look at the picture through Finder (i open the preview pane at the right or add more tabs like "resolution", it simply doesn't show me any EXIF information. Also no EXIF information with CTRL+CMD+I.
On the other hand, when i open the picture with "Preview" and then check the picture information, i see all EXIF like camera, GPS etc...

So it actually seems that EXIF gets exported correctly, but Finder is not showing it? Maybe wait a week for some weird background magic?
Any clue on that?

**Comment by zeroboioioy** [comment] 2023-06-29 07:16
Update: it seems after "some time" Finder is re-indexing the pictures with EXIF information.

Now i only have to fix the "Creation Date" to be the same as in the EXIF data

**Comment by RhetTbull** [comment] 2023-06-29 11:24
Glad you got this working. It's still odd that you're seeing that exiftool warning. Does the warning happen with every photo? 

> Now i only have to fix the "Creation Date" to be the same as in the EXIF data.

You can use the `--touch-file` option with `osxphotos export`  to set the file modification date to match the photo's creation date.

**Comment by zeroboioioy** [comment] 2023-06-29 11:39
Yes, every photo, no matter if jpg or heic.

**Comment by RhetTbull** [comment] 2023-06-29 13:22
If it's happening with every photo it's possible the EXIF data isn't actually being written. Are you certain the EXIF data in the exported photos matches what's in Photos.app and not just what was in the photo before import? For example, if you add a keyword in Photos and export it with `--exiftool`, then that keyword should appear in the EXIF data of the exported photo.

**Comment by zeroboioioy** [comment] 2023-06-30 07:33
Just checked with Keywords and Title and it's all in there, i was able to find the information in the "IPTC" tab of the picture.

And thanks for the "--touch-file" hint, works perfectly!

**Comment by RhetTbull** [comment] 2023-06-30 15:52
I'm glad it's working but also confused by the warning. I'll mark this as a bug for now and will explore when I get  a chance what could be causing the warning.

**Comment by RhetTbull** [comment] 2023-09-03 17:46
> Tried exiftools with option"-v" and it shows the error message with every picture:
WARNING - exiftool.py - 415 - error loading json returned by exiftool: Expecting value: line 1 column 1 (char 0)

I am able to replicate this particular error but it's not a bug. Using exiftool with -v causes the output returned by exiftool to differ from what osxphotos is expecting hence osxphotos cannot parse the data.

As you were able to see the metadata in the photos (thus it's being exported correctly), I'm closing this. If you still are having issues, let me know.

**Closed by RhetTbull** 2023-09-03 17:46 UTC
Labels: bug, cli
