### ISSUE TITLE
Wrong metadata for TIFF modified date

### ISSUE THREAD

**Issue by lukszar** [RhetTbull/osxphotos#247] opened 2020-10-29 19:39 UTC
Recently I found a bug (tested on version 0.36.0). 
Modify Date metadata in exported photos is incorrect -- during export date is set on current date.

Problem exists for photos with .HEIC extension. 
There is photo f.ex. from 2018. Not edited, original.
After export using osxphotos with --exiftool and --touch-file together, exported photo returns such metadata (using exiftool -a -G1 in terminal):

```
[System]        File Modification Date/Time     : 2018:08:17 20:33:43+02:00
[IFD0]          Modify Date                     : 2020:10:29 21:05:28
[ExifIFD]       Date/Time Original              : 2018:08:17 20:33:43
[ExifIFD]       Create Date                     : 2018:08:17 20:33:43
[Composite]     Create Date                     : 2018:08:17 20:33:43.289
[Composite]     Date/Time Original              : 2018:08:17 20:33:43.289+02:00
```

The same photo exported from Photos.app using built-in method returns following metadata in exiftool:

```
[System]        File Modification Date/Time     : 2018:08:17 20:33:43+02:00
[IFD0]          Modify Date                     : 2018:08:17 20:33:43
[ExifIFD]       Date/Time Original              : 2018:08:17 20:33:43
[ExifIFD]       Create Date                     : 2018:08:17 20:33:43
[Composite]     Create Date                     : 2018:08:17 20:33:43.289
[Composite]     Date/Time Original              : 2018:08:17 20:33:43.289
```

Easy to find there is difference in **[IFD0] Modify Date**. Also presented in Information window in Preview.app (tab TIFF).

Many software for photo managing use modify date to sort pictures, then everything starts to be a mess. Unfortunately I don't have any clue how to solve above issue in the code. Let me know if I can provide more info.

**Comment by RhetTbull** [comment] 2020-10-29 19:58
@lukszar thanks for the bug report.  Could you try the following query and let me know what is shown for "date_modified" for this photo:

`osxphotos query --from-date 2018-08-17 --to-date 2018-08-17`

This will dump info on all photos from the date in question.  You should then able to find the filename of the photo in question in the output and see which value is listed in the date_modified column.

**Comment by lukszar** [comment] 2020-10-29 20:08
@RhetTbull thank you for response.

I executed command given by you and results were empty, but I did some checking in advance by changing --to-date in your command (+1day) like following:

`osxphotos query --from-date 2018-08-17 --to-date 2018-08-18`

And it returns this photo. For confirmation I set unique title for this photo so I am 100% sure that it's the one. Results from query:

`6ITsLDRNQoGjD20UUZy2vg,IMG_1588.HEIC,IMG_1588.HEIC,2018-08-17T20:33:43.289000+02:00,,Anaa,Anamaria,Anamaria,_UNKNOWN_,/Users/lszarkowicz/Pictures/Biblioteka Zdjęcia.photoslibrary/Masters/2018/09/06/20180906-064006/IMG_1588.HEIC,False,False,False,False,False,,50.08445833,19.883678330000002,,True,False,public.heic,False,False,,False,,2020-10-29T21:05:28.432738+02:00,False,False,False,False,False,False,False,False,,,False
`

I did also additional tests and modification date is changed just when --exiftool is used.

**Comment by RhetTbull** [comment] 2020-10-29 20:17
Thanks -- this is helpful.  The output shows that `osxphotos` is reporting the date modified is `2020-10-29T21:05:28.432738+02:00` which as you've noted is incorrect.  It also shows that the photo has not been edited and thus should not have a date modified.  This gives me enough information to know where to look in the code.  I'll take a look later this evening.

**Comment by lukszar** [comment] 2020-10-29 20:26
Thank you for your help and wish you luck in your work.

**Comment by RhetTbull** [comment] 2020-10-30 13:31
I think I've figured this out but a fix will take me a few days.

**Comment by RhetTbull** [comment] 2020-10-31 15:32
For future reference:
osxphotos was looking at `ZGENERICASSET.ZMODIFICATIONDATE` for modification date...but that turns out to be incorrect.  Photos sets this value even for photos that have not been edited.  On initial import, it is set to the file modification date.  This value then appears to be updated any time Photos makes a change to the record for that photo even if photo hasn't itself been edited.  I should have been looking at `ZGENERICASSET.ZADJUSTMENTTIMESTAMP` which is only set when the photo is edited.

`ZGENERICASSET.ZMODIFICATIONDATE`: on initial import = file modification date, then updated by Photos as Photos makes changes to the database
`ZGENERICASSET.ZDATECREATED`: EXIF Create Date
`ZGENERICASSET.ZADJUSTMENTTIMESTAMP`: null on import, even if EXIF Modify Date is set, then updated if Photo is edited

If adjustment made, `ZHASADJUSTMENTS` set to 1 and `ZADJUSTMENTTIMESTAMP` set to time of edit
and `ZMODIFICATIONDATE` updated to a time close to, but not exactly the same as `ZADJUSTMENTTIMESTAMP` (in my tests, a few seconds after `ZADJUSTMENTTIMESTAMP`)

On export, Photos does not update the EXIF modify date even if photo has been edited.

**Comment by RhetTbull** [comment] 2020-10-31 15:59
@lukszar  I think this should be fixed now for Catalina in release [v0.36.2](https://github.com/RhetTbull/osxphotos/releases/tag/v0.36.2), still working on Mojave.  Unfortunately, you'll have to do a full export again as `--update` won't catch the changed exifdata in this case.

**Comment by lukszar** [comment] 2020-10-31 17:07
@RhetTbull Thanks, I upgrade osxphotos to 0.36.2 and checked again. 

Photo exported (same as last time) has modification date on `2020-10-29T21:05:28.432738+02:00` -- photo is taken in 2018, no changes. I use `--exiftool` and `--touch-file` together. Is it possible that the fact of adding tag to photo did change modification date in this photo? 

Of course, exporting photo straight from Photos.app results with modification date in 2018 (original date of creation for this photo).

**Comment by RhetTbull** [comment] 2020-10-31 17:15
@lukszar ahh...I just noticed from the debug data you posted earlier you must be running MacOS Mojave (10.14) or ealier?  Can you confirm which version you're using? (I can tell from the UUID field which shows `6ITsLDRNQoGjD20UUZy2vg`  -- Catalina uses a different format.  The fix I pushed only works on Catalina (10.15). I'm still working on the fix for Mojave and earlier.

**Comment by RhetTbull** [comment] 2020-10-31 17:32
Yes, it's possible that adding the tag caused the modification date to change.  There was a bug in osxphotos that used the wrong date from the database.  It's fixed now in MacOS 10.15 but the 10.14 and earlier database format is completely different and I still need to do some reverse engineering to find the problem.

**Comment by RhetTbull** [comment] 2020-10-31 19:09
I've confirmed that on Mojave,`RKVersion.lastModifiedDate` is updated if user adds a tag/keyword:

`UPDATE RKVersion SET lastModifiedDate=625863631.261309, hasKeywords=1, statViewCount=4 WHERE modelId=2;`

I'm sure there are other things (likely adding to albums, etc) that will update `lastModifiedDate` making it unreliable to find out when the photo was actually edited.

I've done several diffs and cannot find any other date value that is specific only to edits (adjustments).  An edit produces a database update similar to this:

`UPDATE RKVersion SET adjustmentUuid='6slTEcx6QEOhreT3Skzl0g', lastModifiedDate=625863895.073802, hasAdjustments=1, previewsAdjustmentUuid='6slTEcx6QEOhreT3Skzl0g', sceneAdjustmentUuid='6slTEcx6QEOhreT3Skzl0g', statViewCount=2, searchIndexInvalid=1 WHERE modelId=1;`

For Mojave and earlier, I think I'll have to look at PhotoInfo.hasadjustments and if True, return `lastModifiedDate` and if not, return `None`.  This means `PhotoInfo.date_modified` won't always be 100% correct for photos that were edited but code will not report erroneous dates for photos that were not edited, as it does now.

**Comment by lukszar** [comment] 2020-10-31 21:43
@RhetTbull Yes, I use Mojave, so I will consider update to Catalina. What about modification date, Photos.app during export do some trick that modification date is correct in not edited photos. Is set on the same date as creation date (maybe it's better than returning none). And what about edited photos, there would be useful some command which would override modification date to the same as creation date (as Synology Moments used by me reorder photos unfortunately by modification date).

**Comment by RhetTbull** [comment] 2020-10-31 22:46
I'm working on a fix to Mojave but it'll have some limitations as described above.  As far as I can tell from testing, Photos sets the modification date to the creation date regardless of whether or not the photo was edited.  I could always return the creation date if photo has not been editing -- I don't really know how other photo software handles this.  To me, setting a modification date implies the photo has been modified but clearly that's not what Photos does.  I could add a flag for exiftool to set the modification date to the creation date in all cases if that fits your use case better. Perhaps `--set-modify-date-to-creation` or `--ignore-modify-date`

**Comment by RhetTbull** [comment] 2020-11-01 01:43
Here's the summary of the testing I've done on Mojave.  Summary: Photos sets several creation/modify dates when exporting but sets them all to creation date regardless of whether the photo has any adjustments.  Results are from `exiftool -G`

MacOS Mojave, Photos 4

Original photo with create date set, no modify date:
```
[EXIF]          Create Date                     : 2020:10:30 00:00:00
```

Export unmodified original from Photos:
```
[EXIF]          Create Date                     : 2020:10:30 00:00:00
```

Export from Photos: 
Several dates are set but all set to Date/Time Original (creation date)
```
[EXIF]          Modify Date                     : 2020:10:30 00:00:00
[EXIF]          Date/Time Original              : 2020:10:30 00:00:00
[EXIF]          Create Date                     : 2020:10:30 00:00:00
[IPTC]          Digital Creation Date           : 2020:10:30
[IPTC]          Date Created                    : 2020:10:30
[Composite]     Date/Time Created               : 2020:10:30 00:00:00
[Composite]     Digital Creation Date/Time      : 2020:10:30 00:00:00
```

Edit image then export from Photos:
Same dates are set even though photo was modified
```
[EXIF]          Modify Date                     : 2020:10:30 00:00:00
[EXIF]          Date/Time Original              : 2020:10:30 00:00:00
[EXIF]          Create Date                     : 2020:10:30 00:00:00
[IPTC]          Digital Creation Date           : 2020:10:30
[IPTC]          Date Created                    : 2020:10:30
[Composite]     Date/Time Created               : 2020:10:30 00:00:00
[Composite]     Digital Creation Date/Time      : 2020:10:30 00:00:00
```

Import a photo that has modify date set:
```
[EXIF]          Modify Date                     : 2020:10:31 10:10:10
[EXIF]          Create Date                     : 2020:10:30 00:00:00
```

Export unmodified original from Photos:
No change
```
[EXIF]          Modify Date                     : 2020:10:31 10:10:10
[EXIF]          Create Date                     : 2020:10:30 00:00:00
```

Export from Photos:
Modify date is overwritten with date/time original / create date
```
[EXIF]          Modify Date                     : 2020:10:30 00:00:00
[EXIF]          Date/Time Original              : 2020:10:30 00:00:00
[EXIF]          Create Date                     : 2020:10:30 00:00:00
[IPTC]          Digital Creation Date           : 2020:10:30
[IPTC]          Date Created                    : 2020:10:30
[Composite]     Date/Time Created               : 2020:10:30 00:00:00
[Composite]     Digital Creation Date/Time      : 2020:10:30 00:00:00
```

Make edit then export from Photos:
Same result
```
[EXIF]          Modify Date                     : 2020:10:30 00:00:00
[EXIF]          Date/Time Original              : 2020:10:30 00:00:00
[EXIF]          Create Date                     : 2020:10:30 00:00:00
[IPTC]          Digital Creation Date           : 2020:10:30
[IPTC]          Date Created                    : 2020:10:30
[Composite]     Date/Time Created               : 2020:10:30 00:00:00
[Composite]     Digital Creation Date/Time      : 2020:10:30 00:00:00
```

**Comment by RhetTbull** [comment] 2020-11-01 05:21
@lukszar OK, I think I've fixed this for Mojave.  I decided to emulate the behavior of Photos with one exception: If a photo has been edited, `osxphotos` will set the exif modification date to the modification date in the database.  If not, `osxphotos` will set exif modification date to the photo creation date as does Photos. `osxphotos` will also now set the following exif fields, just as Photos does:

```
[EXIF]          Modify Date                  
[EXIF]          Date/Time Original       
[EXIF]          Create Date                   
[IPTC]          Digital Creation Date       
[IPTC]          Date Created   
```

**Comment by RhetTbull** [comment] 2020-11-01 05:23
I will still plan to add a flag to `osxphotos` that will cause it to *always* set the modification date to the same as creation date to copy the Photos functionality.

**Comment by RhetTbull** [comment] 2020-11-01 17:19
@lukszar OK, here's what I've done:  if photo has a valid modification date, `--exiftool` will set the modification date accordingly.  If it does not (has not been edited), modification date will be set to original creation date.  I also added a flag in [v0.36.5](https://github.com/RhetTbull/osxphotos/releases/tag/v0.36.5) `--ignore-date-modified`, that modifies this behavior so that the modification date is *always* set to the creation date (this matches the behavior of Photos).

**Comment by lukszar** [comment] 2020-11-03 18:51
@RhetTbull Thanks for improvements. Meanwhile I updated my system so now I am testing on Catalina. 

`--ignore-date-modified` looks nice and works well. 

While my next tests I found that EXIF dates for modified (edited) photos has cut time from date. What results always with 00:00:00 as timestamp (creation and modification EXIF date). I checked on normal export via Photos.app and time is proper (different than 00:00:00). Hopes it will help.

**Comment by RhetTbull** [comment] 2020-11-03 19:58
@lukszar could you post output of following command for one of the photos that's missing modified time:

`exiftool -G -a photoname.jpeg | grep Date`

**Comment by lukszar** [comment] 2020-11-03 20:34
@RhetTbull it's exactly problem with creation date. 
Results pasted below:

```
[File]          File Modification Date/Time     : 2020:09:13 09:33:38+02:00
[File]          File Access Date/Time           : 2020:11:03 21:30:00+01:00
[File]          File Inode Change Date/Time     : 2020:11:03 21:30:00+01:00
[EXIF]          Modify Date                     : 2020:10:29 21:51:03
[EXIF]          Date/Time Original              : 2020:09:13 09:33:38
[EXIF]          Create Date                     : 2020:09:13 09:33:38
[XMP]           Date Created                    : 2020:09:13 09:33:38
[XMP]           Create Date                     : 2020:09:13 09:33:38
[XMP]           Modify Date                     : 2020:09:13 09:33:38
[IPTC]          Digital Creation Date           : 2020:09:13
[IPTC]          Date Created                    : 2020:09:13
[ICC_Profile]   Profile Date Time               : 2017:07:07 13:22:32
[Composite]     Create Date                     : 2020:09:13 09:33:38.785
[Composite]     Date/Time Original              : 2020:09:13 09:33:38.785+02:00
```

**Comment by RhetTbull** [comment] 2020-11-04 02:15
@lukszar Thanks.  Could you send me the output of the same command for the same photo exported from Photos?  On my machine (Catalina 10.15.7), Photos does *not* set the time on `IPTC:DateCreated` or `IPTC:DigitalCreationDate`, it only sets the date and so I emulated this behavior in `osxphotos`.  The [spec](https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#date-created) does allow for time and it would be easy to adjust `osxphotos` to include the time.

**Comment by lukszar** [comment] 2020-11-05 09:50
@RhetTbull here is output for photo exported by Photos.app:

```
[File]          File Modification Date/Time     : 2020:11:03 19:46:16+01:00
[File]          File Access Date/Time           : 2020:11:03 19:46:19+01:00
[File]          File Inode Change Date/Time     : 2020:11:03 19:46:19+01:00
[EXIF]          Modify Date                     : 2020:09:13 09:33:38
[EXIF]          Date/Time Original              : 2020:09:13 09:33:38
[EXIF]          Create Date                     : 2020:09:13 09:33:38
[XMP]           Create Date                     : 2020:09:13 09:33:38
[XMP]           Modify Date                     : 2020:09:13 09:33:38
[XMP]           Date Created                    : 2020:00:09 09:33:38+02:00
[IPTC]          Date Created                    : 2020:09:13
[Composite]     Create Date                     : 2020:09:13 09:33:38.785+02:00
[Composite]     Date/Time Original              : 2020:09:13 09:33:38.785+02:00
[Composite]     Modify Date                     : 2020:09:13 09:33:38+02:00
[Composite]     Date/Time Created               : 2020:09:13 09:33:38+02:00
```

**Comment by RhetTbull** [comment] 2020-11-05 14:19
Thanks.  Looks like the only difference is IPTC:DigitialCreationDate which Photos didn't set in your case but it also did not include the time on IPTC:DateCreated.  I'll play with this some more and set the time wherever exif specifications allow.

**Comment by RhetTbull** [comment] 2020-11-09 05:25
@lukszar I think I may have fixed this.  Turns out I wasn't properly setting IPTC:TimeCreated which is why your photos showed a time of 00:00:00.  When you have time, please try release [v0.36.14](https://github.com/RhetTbull/osxphotos/releases/tag/v0.36.14) and let me know if this fixes the problem.

**Comment by lukszar** [comment] 2020-11-13 19:35
@RhetTbull Thank you for improvements and sorry for delay in response. 

It looks like now it's working properly. Below I paste results:

```
[File]          File Modification Date/Time     : 2020:09:13 09:33:38+02:00
[File]          File Access Date/Time           : 2020:11:13 20:31:49+01:00
[File]          File Inode Change Date/Time     : 2020:11:13 20:31:48+01:00
[EXIF]          Modify Date                     : 2020:09:13 09:33:38
[EXIF]          Date/Time Original              : 2020:09:13 09:33:38
[EXIF]          Create Date                     : 2020:09:13 09:33:38
[XMP]           Date Created                    : 2020:09:13 09:33:38
[XMP]           Create Date                     : 2020:09:13 09:33:38
[XMP]           Modify Date                     : 2020:09:13 09:33:38
[IPTC]          Date Created                    : 2020:09:13
[ICC_Profile]   Profile Date Time               : 2017:07:07 13:22:32
[Composite]     Create Date                     : 2020:09:13 09:33:38.785
[Composite]     Date/Time Original              : 2020:09:13 09:33:38.785+02:00
[Composite]     Date/Time Created               : 2020:09:13 09:33:38+02:00
```

**Closed** 2020-11-13 22:44 UTC
Labels: bug
