### ISSUE TITLE
Crash during export process : can only concatenate str (not "NoneType") to str_

### ISSUE THREAD

**Issue by alban73** [RhetTbull/osxphotos#1643] opened 2024-08-12 18:07 UTC
Hello,

I use the last current version of OSXPHOTOS (0.68.4).

I export correctly many photos (around 50 000), and suddenly, export process crash with the following error :

_Something went wrong and osxphotos encountered an error:
can only concatenate str (not "NoneType") to str_

I cannot tell you if it occurs always on the same picture but it occurs after hours of processing.
Anyways it occurs always during export process.

I attach error log file for further analysis. 
If you have an idea, I would be interested, because I can never finish my exporting process.

Anyway, thanks for you fantastic work with this script.....

Thanks to all,

Alban

[osxphotos_crash.log](https://github.com/user-attachments/files/16590283/osxphotos_crash.log)

**Comment by alban73** [comment] 2024-08-13 05:12
Hello. Thanks for your answer. Of course, I will come back later with the result.

**Comment by alban73** [comment] 2024-08-14 05:41
Hello,
Here is the new log file. Not sure il will be more clear.
Thanks !

[osxphotos_crash.log](https://github.com/user-attachments/files/16608015/osxphotos_crash.log)

**Comment by RhetTbull** [comment] 2024-08-14 11:14
Thanks for the additional data. Unfortunately that didn't give me the details I thought it would but I do see exactly where the problem is occurring. If you're able to run one more command to get additional details that would be helpful. Note that the output of this command may contain sensitive data such as location information so if you'd prefer, you can send it to me at osxphotos.py@gmail.com rather than post here. The command will generate a file `debug.txt` which is what I need.

`osxphotos debug-dump --dump photos --uuid 2841BC31-2C83-4343-BB6C-DE1B0F65B3C3 > debug.txt`

The issue is caused because a photo has been edited but the universal type identifier (UTI) of the edited photo is an expected value. I'm trying to determine what value is in the database for this. OSXPhotos uses this value to know what extension to use for the edited image (this may be required in cases where the edited image is not on the local mac and must be downloaded from iCloud with `--download-missing`.)

**Comment by alban73** [comment] 2024-08-14 15:13
So, debug.txt file, with your command line is nearly empty : 

_Opening database: /Volumes/DISQUE HDD/Photothèque.photoslibrary
Done; took 323.08 seconds_

**But**, I tried the same command line with this UUID : 218D3B6A-A4B2-4088-9B30-2BFEF29490D6 (in my message too). And then it works. File joined.
[debug.txt](https://github.com/user-attachments/files/16615255/debug.txt)

**Comment by alban73** [comment] 2024-08-15 08:13
Hello, just remove the specific picture  ( not important ) , and just trying to launch again process. Keep you in touch.

**Comment by RhetTbull** [comment] 2024-08-15 12:07
Using your additional data was able to figure out which UTI (edited Olympus RAW) was causing the issue and implemented a fix. Should be fixed in release 0.68.5.

@all-contributors please add @alban73  for bug, data

**Closed** 2024-08-15 12:10 UTC
Labels: bug

**Comment by alban73** [comment] 2024-08-15 20:39
Thanks !!!
