### ISSUE TITLE
String index out of range (no extension in photos' original file name)

### ISSUE THREAD

**Issue by carlesbellver** [RhetTbull/osxphotos#570] opened 2022-01-05 15:16 UTC
My Photos library contains a bunch of really old JPEG photos (dating back to the Classic Mac OS days) with no file extension at all in their "original file name". When I try to export the whole library, osxphotos fails to export each one of those photos and outputs the following error message: "String index out of range".

I guess I could fix this problem by appending the extension to the original file name in the Photos.sqlite database. Something like this:

update ZADDITIONALASSETATTRIBUTES set ZORIGINALFILENAME = ZORIGINALFILENAME || '.jpg' where ZORIGINALFILENAME not like "%.%"

But it looks like a dangerous thing to do, and I really don't know.

SW versions:

macOS Monterey 12.0.1
osxphotos 0.44.3

Full command line used:

osxphotos export --update --cleanup --not-hidden --not-shared --not-screenshot --skip-original-if-edited --skip-raw --skip-live --skip-bursts --touch-file --directory '{created.year}/{created.mm}/{created.dd}' --filename "{created.year}-{created.mm}-{created.dd}-{created.hour}-{created.min}-{created.sec}-{id}" "$EXPORT_DIR"

**Comment by RhetTbull** [comment] 2022-01-05 15:52
This is definitely a case osxphotos does not check for. I'll take a look.

> I guess I could fix this problem by appending the extension to the original file name in the Photos.sqlite database. Something like this:

I don't recommend doing this as I don't know what could break in Photos.

**Comment by RhetTbull** [comment] 2022-01-06 14:39
I'm trying to recreate this bug so I can find the cause of the error and fix it but so far I can't reproduce.  

1. I tried to import files with no extension and Photos gave me an "unsupported file type" error
2.  I imported photos then edited the database manually to remove the extension from the ZORIGINALFILENAME field but osxphotos still exports these fine (with no extension...likely not the desired behavior).

It would be helpful to have some additional debug info.  Could you do the following: 

1. Select one of the images in photos, then type this in the command line: `osxphotos query --selected`
2. The first field in the output will be the unique ID (UUID) of the image and it'll look something like `8CAAC794-B2C0-4FFE-B4D6-C98206B43CBE`; copy this value to the clipboard
3.  Then type `osxphotos debug-dump --dump photos --uuid UUID_HERE > debug.txt` (pasting the UUID you copied in step 2)
4. Then post the debug.txt file here.

Note: The debug.txt file may contain information you consider private like locations, names of people or keywords, etc. so I suggest you scan it and remove any of the info you don't want publicly posted.

**Comment by carlesbellver** [comment] 2022-01-06 15:37
Opening database: /Users/imma/Pictures/Fototeca de Fotos.photoslibrary
Done; took 11.95 seconds
_dbphotos['072F3B2E-6081-48AF-A5BC-4C4DAA21D392']:
{'UTI': 'public.jpeg',
 'UTI_original': None,
 'UTI_raw': None,
 '_uuid': '072F3B2E-6081-48AF-A5BC-4C4DAA21D392',
 'added_date': datetime.datetime(2017, 11, 24, 15, 38, 42, 297580),
 'adjustmentFormatID': None,
 'adjustmentUuid': None,
 'albums': [],
 'alt_master_uuid': None,
 'burst': False,
 'burstPickType': 0,
 'burstUUID': None,
 'cloudAssetGUID': '072F3B2E-6081-48AF-A5BC-4C4DAA21D392',
 'cloudAvailable': None,
 'cloudLibraryState': None,
 'cloudLocalState': 3,
 'cloudStatus': None,
 'cloudbatchpublishdate': None,
 'cloudownerhashedpersonid': None,
 'countryCode': None,
 'customRenderedValue': 0,
 'datastore_subtype': None,
 'depth_state': 0,
 'directory': '0',
 'extendedDescription': None,
 'favorite': 0,
 'filename': '072F3B2E-6081-48AF-A5BC-4C4DAA21D392.jpeg',
 'fok_import_session': None,
 'hasAdjustments': 0,
 'hasAlbums': 0,
 'hasKeywords': 0,
 'hasPersons': 1,
 'has_raw': False,
 'hdr': False,
 'height': 1200,
 'hidden': 0,
 'imageDate': datetime.datetime(2000, 12, 10, 18, 40, 32, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600))),
 'imageDate_timestamp': -1837168,
 'imageTimeZoneOffsetSeconds': 3600,
 'import_session': 3,
 'import_uuid': '9D76C4E3-FC6D-47B4-A4F8-D2E891C2B485',
 'incloud': True,
 'intrash': False,
 'isMissing': 0,
 'isreference': False,
 'keywords': [],
 'lastmodifieddate': None,
 'lastmodifieddate_timestamp': None,
 'latitude': None,
 'live_photo': False,
 'localAvailability': 1,
 'longitude': None,
 'masterFingerprint': 'Aev/o68ZZ9CCYa/Wak6ahrDrtU44',
 'masterUuid': None,
 'modelID': None,
 'momentID': 2409,
 'name': None,
 'non_raw_master_uuid': None,
 'orientation': 1,
 'originalFilename': 'foto032',
 'original_filesize': 290259,
 'original_height': 1200,
 'original_orientation': 1,
 'original_resource_choice': 0,
 'original_width': 1600,
 'panorama': False,
 'persons': [54272],
 'pk': 587,
 'placeIDs': None,
 'placeNames': None,
 'portrait': False,
 'raw_data_length': None,
 'raw_info': None,
 'raw_is_original': False,
 'raw_master_uuid': None,
 'remoteAvailability': 1,
 'resource_type': None,
 'reverse_geolocation': None,
 'saved_asset_type': 3,
 'screenshot': False,
 'selfie': False,
 'shared': False,
 'slow_mo': False,
 'subtype': 0,
 'time_lapse': False,
 'trasheddate': None,
 'trasheddate_timestamp': None,
 'type': 0,
 'visibility_state': 0,
 'visible': True,
 'width': 1600}

**Comment by RhetTbull** [comment] 2022-01-07 06:32
@carlesbellver I *think* I've fixed this in [v0.44.5](https://github.com/RhetTbull/osxphotos/releases/tag/v0.44.5).  Update and give it a try and let me know if you're still having problems.

There were a number of changes regarding UTI (which specifies file type) on Monterey that I've not been able to fully test as I don't have a Monterey machine.

**Comment by carlesbellver** [comment] 2022-01-07 07:56
osxphotos upgraded from 0.44.3 to 0.44.6. I can confirm export is working now with those old photos. Exported without extensions, but Finder knows they are JPEG, and Quick Look and Preview handle them too. Thanks!

**Comment by oPromessa** [comment] 2022-01-23 11:41
@carlesbellver and @RhetTbull 

Would go here on a limb and close this `bug` as it is reported as fixed. 

Let me know if you'd not like me to perform such "cleaning" 😉

**Closed** 2022-01-23 15:50 UTC
Labels: bug
