### ISSUE TITLE
json format differences from exiftool

### ISSUE THREAD

**Issue by narensankar0529** [RhetTbull/osxphotos#303] opened 2020-12-27 09:14 UTC
osxphotos seems to add tag-group to the json exports whereas exiftool does not. This makes some software not read the json correctly.

Attached what osxphotos exports as well as what I get from exiftool -j

Have you seen this issue with other software? I am trying to get Photoprism to read the tags but it does not. If you look at all their test json none of them have the prefix tag groups like XMP: or EXIF:

https://github.com/photoprism/photoprism/tree/develop/internal/meta/testdata

[test.json.txt](https://github.com/RhetTbull/osxphotos/files/5744316/test.json.txt)
[nsankar_IMG_2452_2016_Dec_31.JPG.json.txt](https://github.com/RhetTbull/osxphotos/files/5744317/nsankar_IMG_2452_2016_Dec_31.JPG.json.txt)

**Comment by RhetTbull** [comment] 2020-12-27 15:17
The json sidecar was designed for specifically for exiftool and I wasn't aware any other apps would read the exiftool json file.  The json sidecar conforms to what you would get if you used `exiftool -G -j` and I have tested that exiftool reads the json sidecar correctly.

Does PhotoPrism read XMP files?  

I could either add an option to drop the tag group in the exported json or just drop it all together.  Internally, osxphotos uses tag groups in all communication with exiftool because I think it's more precise and deliberate to specify exactly what data to change or read.

**Comment by narensankar0529** [comment] 2020-12-27 15:22
I think due to Google Photos decision to change their pricing model, more and more apps are adding support for importing json files v/s xmp. So Photoprism doesn't have xmp working yet but supports json.

It seems to use the exiftool -j (do not use the -G) command line so the tag groups are not used. 

If there are no other users of the tag group in the exported json, then dropping it would be ok and similar to how most of the apps are handling it for now.

**Comment by RhetTbull** [comment] 2020-12-27 16:38
This makes sense if other programs are using the exiftool json.  I had no idea anything besides exiftool uses these.

**Comment by RhetTbull** [comment] 2020-12-27 22:01
I did a test with Google Photos -- the json files generated by Google Takeout are not the same as those used by exiftool.  exiftool will read some of the fields such as "Description" but the json is unique to Google and most of the fields are not read by exiftool.

```
Tag 'favorited' is not defined
Tag 'favorited' is not defined
Tag 'geoData' is not defined
Tag 'geoData' is not defined
Tag 'geoDataExif' is not defined
Tag 'geoDataExif' is not defined
Tag 'googlePhotosOrigin' is not defined
Tag 'googlePhotosOrigin' is not defined
Tag 'imageViews' is not defined
Tag 'imageViews' is not defined
Tag 'modificationTime' is not defined
Tag 'modificationTime' is not defined
Can't write a structure to XMP-expressionmedia:People
Can't write a structure to XMP-mediapro:People
Can't write a structure to XMP-mediapro:People
Tag 'photoTakenTime' is not defined
Tag 'photoTakenTime' is not defined
```

**Comment by RhetTbull** [comment] 2020-12-27 22:24
This is going to be more difficult than I thought.  Without the tag groups, exiftool does not properly set metadata for QuickTime videos (see #282).  It's not clear if this is a bug in Photos or in exiftool but it took a lot of debugging to get these working and I'm not anxious to change this given that oxphotos has to work with lots of media types.  I might add a new sidecar type (maybe something like `json-no-group` or `json-photoprism`)

**Comment by narensankar0529** [comment] 2020-12-28 01:49
Understand about the issue. So yes - if you can support something like  **json-no-tag-group** that would be great

**Comment by narensankar0529** [comment] 2020-12-28 01:58
Another potential issue with the JSON - 

This is an example from my library exported by osxphotos. It puts the "PersonInImage" in XMP:Subject v/s the Keywords that should be there.

I think this is related to placing the keywords in the DigiKam sub-space v/s the main dc space

[{
    "XMP:TagsList": ["adult", "door", "outdoor", "people"], 
    "IPTC:Keywords": ["adult", "door", "outdoor", "people"], 
    "XMP:PersonInImage": ["Silvia Lin"], 
    "XMP:Subject": ["Silvia Lin"], 
    "EXIF:GPSLatitude": -33.88037166666667, 
    "EXIF:GPSLongitude": 151.21371333333335, 
    "EXIF:GPSLatitudeRef": "S", 
    "EXIF:GPSLongitudeRef": "E", 
    "EXIF:DateTimeOriginal": "2016:12:31 18:14:46", 
    "EXIF:CreateDate": "2016:12:31 18:14:46", 
    "EXIF:OffsetTimeOriginal": "+11:00", 
    "IPTC:DateCreated": "2016:12:31", 
    "IPTC:TimeCreated": "18:14:46+11:00", 
    "EXIF:ModifyDate": "2016:12:31 18:14:46"
}]

**Comment by RhetTbull** [comment] 2020-12-28 02:22
This is fixed in the latest release.  Prior to Catalina, Photos would place keywords in IPTC:Keywords and both keywords and subject in XMP:Subject so I replicated this behavior.  In the latest release of osxphotos, I make IPTC:Keywords == XMP:TagsList == XMP:Subject and only put persons in if the --person-keyword option is used.

**Comment by narensankar0529** [comment] 2020-12-28 04:57
Great! Yes I can see this in the latest release. Awesome.

**Comment by narensankar0529** [comment] 2020-12-28 04:58
Sorry - closed this prematurely. Still hoping for the fix for - json-no-tag-group

**Comment by RhetTbull** [comment] 2020-12-28 16:35
@narensankar0529 I added a new sidecar format `--sidecar exiftool` in [v0.38.15](https://github.com/RhetTbull/osxphotos/releases/tag/v0.38.15).  Let me know if this new format is compatible with PhotoPrism.  It should match the output from `exiftool -j`.  The sidecar filename has the same name (photoname.ext.json) as the JSON sidecar (`--sidecar json`) so the two cannot be used together: you must choose either `--sidecar exiftool` or `--sidecar json`.

**Comment by narensankar0529** [comment] 2020-12-29 13:03
It is missing the exiftool signature - so the following lines should be added -

  "SourceFile": "photo_20080613_iphone_dcce19c188c6cea1a6e5bfc24e31bc15_2008_Jun_13.jpg",
  "ExifToolVersion": 12.00,
  "FileName": "photo_20080613_iphone_dcce19c188c6cea1a6e5bfc24e31bc15_2008_Jun_13.jpg",

**Comment by RhetTbull** [comment] 2020-12-29 14:30
Easy enough to add but does it break anything? In my testing exiftool reads the json files just fine.

**Comment by narensankar0529** [comment] 2020-12-29 14:41
Problem is that apps like photo prism are looking at the signature to determine how to parse the json. Because they are trying to handle json from various sources. So the current json is being rejected.

Thanks!
—————

Naren Sankar

**Comment by RhetTbull** [comment] 2020-12-29 16:00
Fixed in release [0.38.19](https://github.com/RhetTbull/osxphotos/releases/tag/v0.38.19).  

If you run `osxphotos export` with `--update`, it should detect that the sidecars need to be updated and write new sidecar files with the new format.

**Comment by narensankar0529** [comment] 2020-12-29 16:07
Great! Running the test now. But I am getting an error with --exiftool. 

Could not find exiftool. Please download and install from https://exiftool.org/

So one question - how does osxphotos find exiftool? I have it in my path at /usr/local/bin

**Comment by RhetTbull** [comment] 2020-12-29 16:15
osxphotos looks in the path as defined by the shell environment it's running in.   Maybe try closing the terminal and trying again.  Nothing in the exiftool code changed.  I've thought about adding an "--exiftool-path" option to explicitely specify but not had a need for it.

**Comment by RhetTbull** [comment] 2020-12-29 16:18
Here's where osxphotos finds exiftool path:

https://github.com/RhetTbull/osxphotos/blob/1dbf22fdc944b2f38763f94118f40f4138a62975/osxphotos/exiftool.py#L23-L32

**Comment by narensankar0529** [comment] 2020-12-29 16:19
Figured out the issue. It was because I was launching osxphotos from launchd and it was not getting the PATH variable from the environment

**Comment by RhetTbull** [comment] 2020-12-29 17:28
I added `--exiftool-path` to [v0.38.20](https://github.com/RhetTbull/osxphotos/releases/tag/v0.38.20) to optionally specify the exiftool path which may be useful for running from launchd etc.

**Comment by RhetTbull** [comment] 2020-12-29 17:31
>Problem is that apps like photo prism are looking at the signature to determine how to parse the json. Because they are trying to handle json from various sources. So the current json is being rejected.

Internally, osxphotos has a very detailed json format that includes *all* metadata known about the image.  I've thought about adding this as a sidecar option.  I don't know golang so not sure I'd be able to write a parser for PhotoPrism but if someone was so inclined this would be an option that would provide for better preservation of metadata.

**Closed** 2020-12-29 17:58 UTC
Labels: bug, enhancement

**Comment by neilpa** [comment] 2021-01-07 02:01
> Internally, osxphotos has a very detailed json format that includes all metadata known about the image. I've thought about adding this as a sidecar option. I don't know golang so not sure I'd be able to write a parser for PhotoPrism but if someone was so inclined this would be an option that would provide for better preservation of metadata.

I'm quite familiar with go and if I find myself bored one weekend I could take a crack at this. I suspect it shouldn't be that difficult. Also, having discovered PhotoPrism recently I'm interested in its potential.

**Comment by RhetTbull** [comment] 2021-01-07 05:43
The raw json currently looks like this.  This is just the internal metadata that osxphotos tracks for each photo.  It doesn't include any template values produced at export time but those could of course be included fairly easily.  If implemented, would probably want to clean this up a bit to make it more usable (e.g. the faces doesn't include the person name, just the primary key value osxphotos uses to find the person name). Open to suggestions on how to structure the json output but this gives an idea of the data that's available.

```json
[
   {
      "albums" : [
         "Pumpkin Farm",
         "Test Album",
         "Software: (original) Adobe Photoshop CC 2014 (Windows)"
      ],
      "burst" : false,
      "comments" : [],
      "date" : "2018-09-28T16:07:07-04:00",
      "date_modified" : null,
      "description" : "Girl holding pumpkin",
      "exif" : {
         "aperture" : 6.3,
         "bit_rate" : null,
         "camera_make" : "Canon",
         "camera_model" : "Canon EOS 5D Mark IV",
         "codec" : null,
         "duration" : null,
         "exposure_bias" : null,
         "flash_fired" : false,
         "focal_length" : 45,
         "fps" : null,
         "iso" : 100,
         "latitude" : null,
         "lens_model" : "EF24-105mm f/4L IS USM",
         "longitude" : null,
         "metering_mode" : 5,
         "sample_rate" : null,
         "shutter_speed" : 0.00625,
         "track_format" : null,
         "white_balance" : 0
      },
      "external_edit" : false,
      "faces" : [
         {
            "_person_pk" : 5,
            "_pk" : 6,
            "age_type" : 2,
            "asset_uuid" : "D79B8D77-BFFC-460B-9312-034F2877D35B",
            "bald_type" : 3,
            "center" : [
               805,
               576
            ],
            "center_x" : 0.589819140732288,
            "center_y" : 0.718357071280479,
            "eye_makeup_type" : 0,
            "eye_state" : 2,
            "face_rect" : [
               [
                  652.040068916976,
                  423.040068916976
               ],
               [
                  957.959931083024,
                  728.959931083024
               ]
            ],
            "face_type" : null,
            "facial_hair_type" : 1,
            "gender_type" : 1,
            "glasses_type" : 3,
            "hair_color_type" : 3,
            "has_smile" : 1,
            "intrash" : 0,
            "left_eye" : [
               729,
               519
            ],
            "left_eye_closed" : 0,
            "left_eye_x" : 0.534752966533435,
            "left_eye_y" : 0.746229855940627,
            "lip_makeup_type" : 0,
            "manual" : 0,
            "mouth" : [
               803,
               628
            ],
            "mouth_x" : 0.588986073974027,
            "mouth_y" : 0.693317826728696,
            "name" : "Katie",
            "pitch" : 0,
            "quality" : 0.625510454177856,
            "right_eye" : [
               854,
               504
            ],
            "right_eye_closed" : 0,
            "right_eye_x" : 0.625711316150833,
            "right_eye_y" : 0.753608449205738,
            "roll" : 0,
            "size" : 0.149374932698265,
            "smile_type" : 2,
            "source_height" : 2048,
            "source_width" : 1365,
            "uuid" : "3826A656-6375-46BA-B33B-210432844332",
            "yaw" : 0
         }
      ],
      "favorite" : false,
      "filename" : "D79B8D77-BFFC-460B-9312-034F2877D35B.jpeg",
      "folders" : {
         "Pumpkin Farm" : [],
         "Software: (original) Adobe Photoshop CC 2014 (Windows)" : [],
         "Test Album" : []
      },
      "has_raw" : false,
      "hasadjustments" : false,
      "hdr" : false,
      "height" : 2048,
      "hidden" : false,
      "incloud" : null,
      "intrash" : false,
      "iscloudasset" : false,
      "ismissing" : false,
      "ismovie" : false,
      "isphoto" : true,
      "israw" : false,
      "keywords" : [
         "Kids"
      ],
      "labels" : [
         "Pumpkin",
         "People",
         "Child",
         "Outdoor",
         "Land",
         "Vegetable",
         "Recreation",
         "Clothing",
         "Food"
      ],
      "latitude" : 41.256566,
      "library" : "/Users/rhet/Pictures/Test-10.15.7.photoslibrary",
      "likes" : [],
      "live_photo" : false,
      "longitude" : -95.940257,
      "orientation" : 1,
      "original_filename" : "Pumkins2.jpg",
      "original_filesize" : 541174,
      "original_height" : 2048,
      "original_orientation" : 1,
      "original_width" : 1365,
      "panorama" : false,
      "path" : "/Users/rhet/Pictures/Test-10.15.7.photoslibrary/originals/D/D79B8D77-BFFC-460B-9312-034F2877D35B.jpeg",
      "path_edited" : null,
      "path_live_photo" : null,
      "path_raw" : null,
      "persons" : [
         "Katie"
      ],
      "place" : {
         "address" : {
            "city" : "Omaha",
            "country" : "United States",
            "iso_country_code" : "US",
            "postal_code" : "68102",
            "state_province" : "NE",
            "street" : "1801\\u20131899 Harney St",
            "sub_administrative_area" : "Douglas",
            "sub_locality" : "Downtown"
         },
         "address_str" : "1801\\u20131899 Harney St, Omaha, NE  68102, United States",
         "country_code" : "US",
         "ishome" : false,
         "name" : "Omaha, Nebraska, United States",
         "names" : {
            "additional_city_info" : [
               "Downtown"
            ],
            "area_of_interest" : [],
            "body_of_water" : [],
            "city" : [
               "Omaha",
               "Omaha",
               "Omaha"
            ],
            "country" : [
               "United States"
            ],
            "field0" : [],
            "field10" : [],
            "field13" : [],
            "field15" : [],
            "field16" : [],
            "field5" : [],
            "inland_water" : [],
            "ocean" : [],
            "postal_code" : [],
            "region" : [],
            "state_province" : [
               "Nebraska"
            ],
            "street_address" : [
               "1801\\u20131899 Harney St"
            ],
            "sub_administrative_area" : [
               "Douglas"
            ],
            "sub_throughfare" : []
         }
      },
      "portrait" : false,
      "raw_original" : false,
      "score" : {
         "behavioral" : 0,
         "curation" : 0.665637761354446,
         "failure" : -0.000855445861816406,
         "harmonious_color" : 0.07196044921875,
         "highlight_visibility" : 0.0508120428514845,
         "immersiveness" : 0.00245285034179688,
         "interaction" : 0.0199999995529652,
         "interesting_subject" : 0.52490234375,
         "intrusive_object_presence" : -0.0380859375,
         "lively_color" : 0.2432861328125,
         "low_light" : 0.00588607788085938,
         "noise" : -0.00818634033203125,
         "overall" : 0.71630859375,
         "pleasant_camera_tilt" : 0.02142333984375,
         "pleasant_composition" : 0.1434326171875,
         "pleasant_lighting" : 0.1932373046875,
         "pleasant_pattern" : 0.045257568359375,
         "pleasant_perspective" : 0.1903076171875,
         "pleasant_post_processing" : 0.05322265625,
         "pleasant_reflection" : 0.00124740600585938,
         "pleasant_symmetry" : 0.00229454040527344,
         "promotion" : 0,
         "sharply_focused_subject" : 0.336181640625,
         "tastefully_blurred" : 0.544921875,
         "well_chosen_subject" : 0.360107421875,
         "well_framed_subject" : 0.63720703125,
         "well_timed_shot" : 0.2373046875
      },
      "screenshot" : false,
      "search_info" : {
         "activities" : [],
         "bodies_of_water" : [],
         "city" : "Douglas",
         "country" : "United States",
         "holidays" : [],
         "labels" : [
            "Pumpkin",
            "People",
            "Child",
            "Outdoor",
            "Land",
            "Vegetable",
            "Recreation",
            "Clothing",
            "Food"
         ],
         "locality_names" : [
            "Omaha"
         ],
         "media_types" : [],
         "month" : "September",
         "neighborhoods" : [
            "Downtown"
         ],
         "place_names" : [],
         "season" : "Fall",
         "state" : "Nebraska",
         "state_abbreviation" : "",
         "streets" : [
            "Harney St"
         ],
         "venue_types" : [],
         "venues" : [],
         "year" : "2018"
      },
      "selfie" : false,
      "shared" : false,
      "slow_mo" : false,
      "time_lapse" : false,
      "title" : "I found one!",
      "uti" : "public.jpeg",
      "uti_original" : "public.jpeg",
      "uti_raw" : null,
      "uuid" : "D79B8D77-BFFC-460B-9312-034F2877D35B",
      "width" : 1365
   }
]
```
