### ISSUE TITLE
archive function

### ISSUE THREAD

**Issue by Se7enair** [RhetTbull/osxphotos#721] opened 2022-06-22 15:04 UTC
**Is your feature request related to a problem? Please describe.**
At the moment not related to a problem. But a possible reason could be, that the space on iCloud is full, or there is no spce left on the mac and older photos should be archived on a network share.

**Describe the solution you'd like**
A function which downloads specific photos and delete them from Apple Photos
`osxphotos archive --album "My first Album"` or `osxphotos archive --to-date 2018-12-31`

Best would be, if I can store them in the same directory as another export is saved. But together with `cleanup` this could be difficult to achieve. So a separate directory is also nice. Or combine `export` with `--archive`.

**Describe alternatives you've considered**
At the moment I use export to a separate folder and delete the photos manually in Apple Photos.

**Additional context**
Could be difficult, because I dont know if there even is a option to delete photos. Without deleting the normal export without cleanup and manual deleting in Apple Photos should do the same.
Another important point is, that sometime I want to archive photos older then a specific year, but keep a single album with pictures that are older. At the moment the export function is not able to select photos older then a specific date and exclude a album.

**Comment by RhetTbull** [comment] 2022-06-22 21:24
This is an interesting use case. Here are a few thoughts:

osxphotos cannot currently delete photos. The AppleScript interface used by osxphotos to to interact with Photos does not support deletion.  It would be possible to implement deletion using the [photokit deleteAssets](https://developer.apple.com/documentation/photokit/phassetchangerequest/1624062-deleteassets?language=objc) interface but so far, I've tried to make sure that osxphotos does not modify the library (except in very specific cases like `osxphotos timewarp`) because I want to make sure that users cannot accidently lose photos.

Exporting the archive to the same folder as the "normal" export would be possible with changes to the code but currently, as you've noted, it is not compatbile with `--cleanup`.  One possible implementation option would be to allow a `--archive` or `--no-cleanup` option on export that would mark all exported files as archived in the export database and then make sure that `--cleanup` does not delete any files marked as archived.  A cleaner solution is to just archive to a different folder. E.g. have something like:

-  Export: `/path/to/photos/export`
- Archive: `/path/to/photos/archive`

You can achieve something close to what you want today using the following options:

```
osxphotos export /path/to/archive \
--added-before 2020-01-01 \
--query-eval " 'Keep Album' not in photos.albums" \
--add-exported-to-album "Archived Photos"
```

I'm not at my Mac so can't verify the `--query-eval` but I think this will exclude any photo in the album `Keep Album` from the export set.

The `--add-exported-to-album "Archived Photos"` will add any exported photo to the album (and create the album if necessary) "Archived Photos".  You can then go into Photos, open the album, select all photos (`Cmd+A`) and then delete the. photos (`Cmd+Option+Delete`).  Note: If you use `Delete` in an Album, the photo is only deleted from the album, not the Photo Library so you need to use `Cmd+Option+Delete`.

**Comment by RhetTbull** [comment] 2022-06-23 05:21
I confirmed the `--query-eval` option above and fixed an error.  As written above, these options should accomplish pretty close to what you are asking: export all photos older than a certain date with exception of those in a certain album then add these photos to a new album so they can be easily deleted.

**Comment by Se7enair** [comment] 2022-06-24 09:44
This is what I want, perfect! 

But how can I add multiple albums to `--query-eval`? Do I have to use it multiple times, or can I combine multiple albums into one ?

**Comment by Se7enair** [comment] 2022-06-24 09:50
Ok, got it for my config
`query_eval = ["'Archiv' not in photo.albums",  'Archiv' not in photo.albums"]`

Its important that you exclude the archive album too, because if it is not empty, it will be exported too.

**Comment by RhetTbull** [comment] 2022-06-24 13:24
Great! Yes, as you figured out you can specify multiple `--query-eval` values by repeating it on the command line or using the list syntax in the toml file as you did. I had not thought about also excluding the archive album so good catch!

**Comment by RhetTbull** [comment] 2022-07-24 11:49
The `--keep` or `--skip-cleanup` in #730 will allow (when implemented) the archive folder to be kept when using `--cleanup`

**Comment by RhetTbull** [comment] 2022-07-24 11:50
@all-contributors please add @Se7enair for ideas

**Closed by RhetTbull** 2022-07-24 11:49 UTC
Labels: duplicate, feature request

**Comment by RhetTbull** [comment] 2022-07-27 16:42
@Se7enair I've added a `--keep` option to `osxphotos export` in [v0.50.10](https://github.com/RhetTbull/osxphotos/releases/tag/v0.50.10) that should allow you to keep the archive folder in the same directory as your export.  You'll need to specify either filenames, a wildcard, or a directory to keep (and you can repeat `--keep` to specify more than one).  For example, if your archive is in `/Volumes/Photos/Archive` and your export is to `/Volumes/Photos`, you can now do this:

`osxphotos export /Volumes/Photos ...other options... --cleanup --keep Archive`

and nothing in `/Volumes/Photos/Archive` will be deleted.

```
--keep KEEP_PATH
                                When used with --cleanup, prevents file or directory KEEP_PATH from being
                                deleted when cleanup is run. Use this if there are files in the export
                                directory that you don't want to be deleted when --cleanup is run. KEEP_PATH
                                may be a file path, e.g. '/Volumes/Photos/keep.jpg',
                                or a file path and wild card, e.g. '/Volumes/Photos/*.txt', or a directory,
                                e.g. '/Volumes/Photos/KeepMe'. KEEP_PATH may be an absolute path or a
                                relative path. If it is relative, it must be relative to the export
                                destination. For example if export destination is `/Volumes/Photos` and you
                                want to keep all `.txt` files, you can specify
                                `--keep "/Volumes/Photos/*.txt"` or `--keep "*.txt"`. If wild card is used,
                                KEEP_PATH must be enclosed in quotes to prevent the shell from expanding the
                                wildcard, e.g. `--keep "/Volumes/Photos/*.txt"`. If KEEP_PATH is a
                                directory, all files and directories contained in KEEP_PATH will be kept.
                                --keep may be repeated to keep additional files/directories.
```
