### ISSUE TITLE
--cleanup option deletes files just added by export/--update. Maybe related with accented album names? 

### ISSUE THREAD

**Issue by oPromessa** [RhetTbull/osxphotos#561] opened 2021-12-28 14:34 UTC
**SUPER WORK! EXCELLENT TOOL!!!**

**Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version**
   * Running version 0.43.8

**Describe the bug**
Following an export and update of the albums; it then goes into the cleanup activity and deletes files that where just loaded.
It only removes the files and then album folder (when they become empty) for some Albums. Only thing I can note is that the Album's names are accented.

**To Reproduce**
1. What' the full command line you used with osxphotos?
   * `osxphotos export /Volumes/photo-1/Family.Photos --db "/Users/Shared/Pictures/iPhoto Shared Library.photoslibrary" --load-config colibri.toml  > so.log 2>se.log &`
   *  `colibri.toml` is as follows
```
[export]
cleanup = true
directory = "{album[/,.|:,.]}"
exiftool = true
exiftool_merge_keywords = true
exiftool_merge_persons = true
from_date = 2021-01-01T00:00:00
keyword_template = [ "{keyword}",]
report = "colibri.csv"
skip_original_if_edited = true
strip = true
update = true
verbose = true
```
2. What was the error output?

**Expected behavior**
Would expect the *just* uploaded files *not* to be deleted.

**Screenshots**
Please note the sample std output I get. You can see the pic `DSC03660.JPG` being exported and then being deleted.
```
Loaded options from file colibri.toml
osxphotos version 0.43.8
exiftool path: /usr/local/bin/exiftool
Using export database /Volumes/photo-1/Family.Photos/.osxphotos_export.db
Processing database /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary/database/photos.db
Processing database /Users/Shared/Pictures/iPhoto Shared Library.photoslibrary/database/Photos.sqlite
Database locked, creating temporary copy.
Processing database.
Database version: 6000, 7.
Processing persons in photos.
Processing detected faces in photos.
Processing albums.
Processing keywords.
Processing photo details.
Processing import sessions.
Processing additional photo details.
Processing face details.
Processing photo labels.
Processing EXIF details.
Processing computed aesthetic scores.
Processing comments and likes for shared photos.
Processing moments.
Done processing details from Photos library.
Exporting 3099 photos to /Volumes/photo-1/Family.Photos...

(...)

Exporting DSC03660.JPG (DSC03660.JPG) as DSC03660.JPG
Writing metadata with exiftool for /Volumes/photo-1/Family.Photos/2021-04-09 Tróia/DSC03660.JPG
Exported new file /Volumes/photo-1/Family.Photos/2021-04-09 Tróia/DSC03660.JPG

(...)

Processed: 3099 photos, exported: 622, updated: 0, skipped: 2477, updated EXIF data: 622, missing: 0, error: 0
Elapsed time: 2712.842 seconds
Cleaning up /Volumes/photo-1/Family.Photos
Deleting /Volumes/photo-1/Family.Photos/2021-04-09 Tróia/DSC03660.JPG
Deleting /Volumes/photo-1/Family.Photos/2021-04-09 Tróia/DSC03628.JPG
Deleting /Volumes/photo-1/Family.Photos/2021-04-09 Tróia/DSC03663.JPG
(...)
```

**Desktop (please complete the following information):**
 - OS: [e.g. which version of macOS]: macOS Monterey 12.1
 - osxphotos version (`osxphotos --version`): 0.43.8

**Additional context**
   * I'm exporting into a mounted volume off a Synology DSM 7 NAS Server.
   * The locale settings are as follows
```
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```
   * Tried to reproduce with just a single Album (accented) but was not exactly able to. Will run more tests!
   * Also note all my files is Photos are "Referenced" files and the library was migrated from iPhoto.
   * Looking for file `DSC03660` on dates file `.osxphotos_export.db` I get:
```
5874|2021-04-09 Tróia/DSC03660.JPG|2021-04-09 tróia/dsc03660.jpg|48624BED-877B-46BF-B03A-B91D762EE371|32768|4548022|1618136601.0|32768|4493835|1618136601.0
```

**Comment by RhetTbull** [comment] 2021-12-28 20:06
Thanks for the detailed bug report. It's quite possible this has to do with accented characters -- Unicode characters have been at the root of several osxphotos issues, partly because the representation used by Photos is at times different than that used by the filesystem.  The test suite already uses albums with accented characters to catch this sort of thing but it's possible there are still edge cases. I'll see if I can reproduce this.

**Comment by RhetTbull** [comment] 2021-12-29 00:13
I was able to replicate this in an album with accented characters.  Now I just need to track down why this is happening...

**Comment by RhetTbull** [comment] 2021-12-29 01:26
@all-contributors add @oPromessa for bug

**Comment by RhetTbull** [comment] 2021-12-29 01:37
I think this is fixed in v0.43.9

**Comment by oPromessa** [comment] 2021-12-29 01:39
Super. Will upgrade and try it out!

**Comment by oPromessa** [comment] 2021-12-29 02:18
Seems to have done the trick! Thanks for the prompt reply!

**Comment by oPromessa** [comment] 2022-02-02 18:48
Hi there. Sorry to bother.

Still related to this I have an album:
* with accented characters `Água` 
* but not only that but it also contains multiple pics (3x) with the same name, e.g. `AAF035.jpg`
* My files are all reference files. So their original location is in different folders, or course!

**I'm testing exporting to the MAC local disk to avoid conflicts on accessing remote folders with other issues** 

### First run I make it correctly generates new names for the 3 files.
```
Água/AAF035 (1).jpg
Água/AAF035 (2).jpg
Água/AAF035.jpg
```

### Second time around two new files are created and the previous two are deleted.
```
Água/AAF035 (3).jpg
Água/AAF035 (4).jpg
Água/AAF035.jpg
```
```
Deleting /Users/(...)/Água/AAF035 (1).jpg
Deleting /Users/(...)/Água/AAF035 (2).jpg
```

### Third run it does a similar process.
```
Água/AAF035 (1).jpg
Água/AAF035 (2).jpg
Água/AAF035.jpg
```
```
Deleting /Users/(...)/Água/AAF035 (3).jpg
Deleting /Users/(...)/Água/AAF035 (4).jpg
```

**Let me know If I can run it in debug mode to collect more traces to facilitate troubleshooting**

**Comment by oPromessa** [comment] 2022-02-02 19:38
No worries. No stress here.

Would the option `--overwrite`  help?

**Comment by RhetTbull** [comment] 2022-02-04 13:40
I *think* [0.45.4](https://github.com/RhetTbull/osxphotos/releases/tag/v0.45.4) fixes the problem with files and albums with accented characters.  I tested the exact situation you described with accented album name and photos containing the same name and it works as expected. Please upgrade and give that a try.

**Comment by oPromessa** [comment] 2022-02-05 10:42
I've ran some tests and limited the export to just the 3 files (with `--regex` on template  `"{album}/{name}"` -- which works like a charm. YAY!!)

With `0.45.4` problem still seems to persist. 

```
2022-02-05 10:29:39.666436 -- Loaded options from file colibri.toml
2022-02-05 10:29:39.666522 -- osxphotos version 0.45.4
2022-02-05 10:29:39.670758 -- Using export database /Users/Shared/Pictures/Export/Photos.2021/Test.Album/.osxphotos_export.db
(...)
2022-02-05 10:30:04.980072 -- Done processing details from Photos library.
Exporting 3 photos to /Users/Shared/Pictures/Export/Photos.2021/Test.Album...
2022-02-05 10:30:52.499233 -- Exporting AAF035.jpg (AAF035.jpg) as AAF035.jpg (1/3)
2022-02-05 10:30:52.505697 -- Skipped up to date file /Users/Shared/Pictures/Export/Photos.2021/Test.Album/Água/AAF035.jpg
2022-02-05 10:30:52.506755 -- Exporting AAF035.jpg (AAF035.jpg) as AAF035.jpg (2/3)
2022-02-05 10:30:52.816523 -- Writing metadata with exiftool for AAF035 (3).jpg
2022-02-05 10:30:53.027365 -- Exported new file /Users/Shared/Pictures/Export/Photos.2021/Test.Album/Água/AAF035 (3).jpg
2022-02-05 10:30:53.027687 -- Touched date on file /Users/Shared/Pictures/Export/Photos.2021/Test.Album/Água/AAF035 (3).jpg
2022-02-05 10:30:53.029392 -- Exporting AAF035.jpg (AAF035.jpg) as AAF035.jpg (3/3)
2022-02-05 10:30:53.133867 -- Writing metadata with exiftool for AAF035 (4).jpg
2022-02-05 10:30:53.254227 -- Exported new file /Users/Shared/Pictures/Export/Photos.2021/Test.Album/Água/AAF035 (4).jpg
2022-02-05 10:30:53.254284 -- Touched date on file /Users/Shared/Pictures/Export/Photos.2021/Test.Album/Água/AAF035 (4).jpg
Processed: 3 photos, exported: 2, updated: 0, skipped: 1, updated EXIF data: 2, missing: 0, error: 0, touched date: 2
Elapsed time: 0:00:00
Cleaning up /Users/Shared/Pictures/Export/Photos.2021/Test.Album
2022-02-05 10:30:53.254845 -- Deleting /Users/Shared/Pictures/Export/Photos.2021/Test.Album/Água/AAF035 (1).jpg
2022-02-05 10:30:53.255010 -- Deleting /Users/Shared/Pictures/Export/Photos.2021/Test.Album/Água/AAF035 (2).jpg
Deleted: 2 files, 0 directories
```

**Comment by RhetTbull** [comment] 2022-02-05 16:30
This was a hard one to track down!  I think I've finally fixed it.  Working on cleaning up the test cases since I had to modify the test Photos libraries.  I created a special test case using the settings from your .toml and the same album/filenames just to be sure this worked. 

```
tests/test_cli.py::test_export_cleanup_exiftool_accented_album_name_same_filenames PASSED                                            [100%]
```

The problem was unicode representation in the export database--sqlite wasn't using the same representation as the file system. I've normalized unicode everywhere I can think of now.  

But...this means your export db will be invalid and you'll still have the issue when you update until the second update which will have the fixed filenames recorded in the export db.

**Comment by RhetTbull** [comment] 2022-02-05 16:55
> But...this means your export db will be invalid and you'll still have the issue when you update until the second update which will have the fixed filenames recorded in the export db.

Never mind....I built a migration into the ExportDB() class so it'll automatically normalize all the old filenames if needed :-)

**Comment by oPromessa** [comment] 2022-02-05 16:56
Cool. Sorry for that!

1. For "update until the second updated which"... it-s okay. It-a about 160 or so pics in that situation. That's fine.
2. For the `export db will be invalid`... 
   1. invalid only for the **same name pics**
      1. This case would be fine as I can run the --update a couple of times and get the 160 or so pics fixed!
   2. of invalid for **all the pics**
      1. In this case, if I delete the `.osxphotos_export.db` file and keep the files already copied on the destination:
         1. Would osphotos simply rebuild the database without copying the files?
         2. Or I'll simply have to delete everything and restart the whole copy?

FYI, as you mentioned the `.toml` file. I've added a few flags which I feel _would not impact the scenario_ but  just in case here are the additional fields/options.

```
touch_file = true
not_hidden = true
```

**Comment by RhetTbull** [comment] 2022-02-05 16:58
> FYI, as you mentioned the .toml file. I've added a few flags which I feel would not impact the scenario but just in case here are the additional fields/options.

Thanks -- I'll add those just in case! 

With the automatic migration, yes, everything should "just work" with the next update.

**Comment by RhetTbull** [comment] 2022-02-05 18:54
I think it's fixed for real in [v0.45.5](https://github.com/RhetTbull/osxphotos/releases/tag/v0.45.5).  Give that a try and let me know if it works!

**Comment by oPromessa** [comment] 2022-02-05 18:55
On it...

**Comment by oPromessa** [comment] 2022-02-05 19:14
On my `small test` with previously exported pics he kept the numbering that was already there `(3)` and `(4)`.

Ran it three times with same result. 
* So we have he issue solved.
* The naming is not as per the _minimum_ which should have been `Água/AAF035 (1).jpg` and `Água/AAF035 (1).jpg` but on a **fresh** copy it works as expected. Don't believe this to be an issue.
* Will run it on the larger set...

```
Água/AAF035 (3).jpg
Água/AAF035 (4).jpg
Água/AAF035.jpg
```

**Comment by RhetTbull** [comment] 2022-02-05 19:19
> The naming is not as per the minimum which should have been Água/AAF035 (1).jpg and Água/AAF035 (1).jpg but on a fresh copy it works as expected. Don't believe this to be an issue.

Yeah, I can't really resolve that easily without really complicating the code that matches existing files to photos.

**Comment by oPromessa** [comment] 2022-02-05 19:19
No worries. It's just great as it is!

**Closed** 2022-02-27 15:28 UTC
Labels: bug
